version: '3.3'


services:
  web:
    build: .
    command: >
      sh -c "gunicorn fullstack.wsgi:application --bind 0.0.0.0:8000"

    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - migration

  db:
    image: postgres
    restart: always
#    ports:
#      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: fullstack
      POSTGRES_USER: stateonuris
      POSTGRES_PASSWORD: 1

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
#    ports:
#      - "6379:6379"
    expose:
      - 6379

  celery:
    build: .
    command: celery -A fullstack worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis

  migration:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

